[package]
authors = ["yuu0141 <https://github.com/Eddio0141>"]
description = "A tool to set up UniTAS for some unity games"
edition = "2021"
name = "unitas_setup_tool"
publish = false
version = "1.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = {version = "4.3.11", features = ["derive"]}
dirs = "5.0.1"
env_logger = "0.10.0"
goblin = "0.7.1"
log = "0.4.19"
pelite = "0.10.0"
reqwest = "0.11.18"
serde = {version = "1.0.164", features = ["derive"]}
serde_json = "1.0.99"
thiserror = "1.0.40"
tokio = {version = "1.28.2", features = ["rt", "fs", "macros", "rt-multi-thread"]}
zip = "0.6.6"
